create table seasons(
    id integer primary key generated by default as identity, 
    title text not null, 
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete cascade, 
    "installmentId" integer not null references installments(id) on delete cascade
);

create table books(
    id integer primary key generated by default as identity, 
    title text not null, 
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete cascade, 
    "installmentId" integer not null references installments(id) on delete cascade
);

create table arcs(
    id integer primary key generated by default as identity, 
    title text not null, 
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete cascade, 
    "installmentId" integer not null references installments(id) on delete cascade
);

create table movies(
    id integer primary key generated by default as identity, 
    title text not null, 
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete cascade, 
    "installmentId" integer references installments(id) on delete cascade
);