create table episodes(
    id integer primary key generated by default as identity, 
    title text not null,
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete set null, 
    "seasonId" integer references seasons(id) on delete cascade 
);

create table issues(
    id integer primary key generated by default as identity, 
    title text not null,
    "order" integer not null, 
    "reviewId" integer references reviews(id) on delete set null, 
    "arcId" integer references arcs(id) on delete cascade 
);