insert into tags(title)
values
('Suspense-Thrillers'),
('Animal Action Films'),
('Biker'),
('Blockbuster'),
('Chase Films or Thrillers'),
('Comic-Book Action'),
('Conspiracy Thriller'),
('(aka Paranoid Thriller)'),
('Costume Adventures'),
('Desert Epics'),
('Epic Adventure Films'),
('Erotic Thrillers'),
('Escape'),
('Girls With Guns'),
('Guy Films'),
('Heroic Bloodshed Films'),
('Hong Kong'),
('James Bond Series'),
('Jungle and Safari Epics'),
('Man or Woman-In-Peril'),
('Man vs. Nature'),
('Martial Arts'),
('Mountain'),
('Political Conspiracies, Thrillers'),
('Rape and Revenge Films'),
('Sea Adventures'),
('Searchers/Expeditions for Lost Continents'),
('Serialized films'),
('Space Adventures'),
('Straight Action/ Conflict'),
('Surfing or Surf Films'),
('Survival'),
('Swashbuckler'),
('Sword and Sorcery'),
('Techno-Thrillers'),
('Treasure Hunts'),
('Undercover'),
('Anarchic Comedies'),
('Animals'),
('Black Comedies (Dark Humor)'),
('British Humor'),
('Classic Comedies'),
('Clown'),
('Comedy Thrillers'),
('Comic Criminals'),
('Dumb Comedies'),
('Family Comedies'),
('Farce'),
('Fish-out-of-water Comedies'),
('Gross-out Comedies'),
('Lampoon'),
('Meet-Cute Screwball or'),
('Romantic Comedies'),
('Mockumentary (Fake Documentary)'),
('Parenthood Comedies'),
('Parody'),
('Political Comedies'),
('Populist'),
('Pre-Teen Comedies'),
('Re-Marriage Comedies'),
('Satire'),
('School Days'),
('Screwball Comedies'),
('Sex Comedies'),
('Slacker'),
('Slapstick'),
('Social-Class Comedies'),
('Sophisticated Comedies'),
('Spoofs'),
('Stand-Up'),
('Stoner Comedies'),
('Teen/Teen Sex Comedies'),
('Urban Comedies'),
('Crime & Gangster'),
('Bad Girl Movies'),
('Cops & Robbers'),
('Detective/Private Eye/Mysteries'),
('Film Noir'),
('Hard-boiled Detective'),
('Law and Order'),
('Lovers on the Run'),
('Mysteries'),
('Neo-Noir'),
('Outlaw Biker Films'),
('Procedurals'),
('Suspense-Thrillers'),
('Trial Films'),
('Vice Films'),
('Victim'),
('Drama'),
('Adaptations, Based upon True Stories'),
('Addiction and/or Alcoholism'),
('Adult'),
('African-American'),
('British Empire'),
('Chick Flicks or Guy-Cry Films'),
('Childhood Dramas'),
('Christmas Films'),
('Costume Dramas'),
('Diary Films'),
('Disease/Disability'),
('Docu-dramas'),
('Ethnic Family Saga'),
('Euro-Spy Films'),
('Fallen Women'),
('Generation Gap'),
('High School'),
('Holocaust'),
('Investigative Reporting'),
('Legal/Courtroom'),
('Life Story'),
('Love'),
('Medical'),
('Melodramas'),
('Newspaper'),
('Nostalgia'),
('Presidential Politics or'),
('Political Dramas'),
('Prostitution'),
('Gay and Lesbian'),
('Race Relations,'),
('Inter-racial Themes'),
('Sexual/Erotic'),
('(Steamy Romantic Dramas)'),
('Shakespearean'),
('Showbiz Dramas'),
('Small-town Life'),
('Soap Opera'),
('Social Problem Film'),
('Social Commentaries'),
('Teen (or Youth) Films'),
('Tragedy'),
('Womens Friendship'),
('Youth Culture'),
('Epic/Historical'),
('Biblical'),
('Greek Myth'),
('Medieval (Dark Ages)'),
('Roman Empire'),
('Horro'),
('B-Movie Horror'),
('Cannibalism or Cannibal Films'),
('Classic Horror'),
('Creature Features'),
('Demonic Possession'),
('Erotic'),
('Ghosts'),
('Gore'),
('Gothic'),
('Halloween'),
('Haunted House, other Hauntings'),
('Macabre'),
('Older-Woman-In-Peril Films'),
('Hagsploitation'),
('Psychic Powers'),
('Reincarnation'),
('Satanic Stories'),
('Serial Killers'),
('Slashers or "Splatter" Films'),
('Teen Terror ("Teen Screams")'),
('Terror'),
('Vampires'),
('Witchcraft'),
('Wolves, Werewolves'),
('Musical/Dance'),
('Ballet'),
('Beach Party Films'),
('Broadway Show Musicals'),
('Concert Films'),
('Dance Films'),
('Folk Musicals'),
('Hip-Hop Films'),
('Operettas'),
('Rockumentary'),
('Stage Musicals'),
('Science Fiction'),
('50s Sci-Fi'),
('Action Sci-Fi'),
('Aliens, Extra-Terrestrial Encounters'),
('Atomic Age'),
('Classic Sci-Fi'),
('Cyber Punk'),
('End of World'),
('Fantasy Films'),
('Lost Worlds'),
('Other Dimensions'),
('Outer Space'),
('Post-Apocalyptic'),
('Pre-historic'),
('Robots, Cyborgs,'),
('and Androids'),
('Sci-Fi Thrillers'),
('Star Trek'),
('Time or Space Travel'),
('Virtual Reality'),
('War'),
('Aerial Combat, Aviation'),
('Anti-War'),
('Civil War'),
('Korean'),
('Prisoner of War/Escape'),
('Revolutionary War'),
('Submarine'),
('Vietnam'),
('Western'),
('Cattle Drive'),
('Epic Westerns'),
('Frontier'),
('Gunfighters'),
('Outlaws'),
('Road-Trail Journeys'),
('Shoot-outs'),
('Spaghetti Westerns'),
('Action Combat'),
('Action Comedies'),
('Alien Invasion'),
('Autobiographic/Biographies'),
('Blaxploitation'),
('Buddy'),
('Buddy Cop'),
('Caper'),
('Comedy Musicals'),
('Coming of Age'),
('Crime Dramas'),
('Crime/Caper Comedies'),
('Disaster'),
('Dramatic Musicals'),
('Espionage'),
('Fairy Tale'),
('Frankenstein/Mad Scientist'),
('Futuristic'),
('Heist/Caper'),
('Historical'),
('Hood Films'),
('Horror Comedies'),
('Indian War/History'),
('Literary Adaptation'),
('Mafia, Organized Crime, Mob Films'),
('Military'),
('Monsters/Mutants'),
('Period Pictures'),
('Prison'),
('Psychological'),
('Quest'),
('Religious'),
('Road'),
('Romance'),
('Sci-Fi Action'),
('Science-Fiction Westerns'),
('Space Adventures'),
('Space Opera'),
('Space Westerns'),
('Spoof Westerns'),
('Sports'),
('Super-Heroes'),
('Supernatural'),
('War'),
('Western Comedies'),
('Western Musicals'),
('Women in Prison'),
('World War I'),
('World War II'),
('Amy Adams'),
('Jessica Alba'),
('Julie Andrews'),
('Jennifer Aniston'),
('Alan Arkin'),
('Kevin Bacon'),
('Eric Bana'),
('Anne Bancroft'),
('Antonio Banderas'),
('Drew Barrymore'),
('Kim Basinger'),
('Annette Bening'),
('Ingrid Bergman'),
('Halle Berry'),
('Juliette Binoche'),
('Cate Blanchett'),
('Orlando Bloom'),
('Humphrey Bogart'),
('Helena Bonham Carter'),
('Ernest Borgnine'),
('Zach Braff'),
('Kenneth Branagh'),
('Marlon Brando'),
('Jeff Bridges'),
('Matthew Broderick'),
('Adrien Brody'),
('Pierce Brosnan'),
('Yul Brynner'),
('Sandra Bullock'),
('Ellen Burstyn'),
('Richard Burton'),
('James Caan'),
('Nicolas Cage'),
('James Cagney'),
('Michael Caine'),
('Steve Carell'),
('Dana Carvey'),
('Jim Carrey'),
('James Caviezel'),
('Stockard Channing'),
('Chevy Chase'),
('Montgomery Clift'),
('George Clooney'),
('Glenn Close'),
('Jennifer Connelly'),
('Sean Connery'),
('Bradley Cooper'),
('Gary Cooper'),
('Kevin Costner'),
('Joan Crawford'),
('Bing Crosby'),
('Russell Crowe'),
('Tom Cruise'),
('Penelope Cruz'),
('Billy Crystal'),
('Tony Curtis'),
('John Cusack'),
('Elisha Cuthbert'),
('Matt Damon'),
('Bette Davis'),
('Geena Davis'),
('Doris Day'),
('James Dean'),
('Patrick Dempsey'),
('Judi Dench'),
('Olivia De Havilland'),
('Johnny Depp'),
('Danny DeVito'),
('Cameron Diaz'),
('Leonardo DiCaprio'),
('Matt Dillon'),
('Robert De Niro'),
('Kirk Douglas'),
('Michael Douglas'),
('Robert DowneyJr.'),
('Richard Dreyfuss'),
('Hilary Duff'),
('Faye Dunaway'),
('Robert Duvall'),
('Michael Clarke Duncan'),
('Kirsten Dunst'),
('Clint Eastwood'),
('Colin Farrell'),
('Will Ferrell'),
('Sally Field'),
('Ralph Fiennes'),
('Albert Finney'),
('Linda Fiorentino'),
('Laurence Fishburne'),
('Carrie Fisher'),
('Jane Fonda'),
('Harrison Ford'),
('Jodie Foster'),
('Jamie Foxx'),
('Morgan Freeman'),
('Clark Gable'),
('Judy Garland'),
('James Garner'),
('Jennifer Garner'),
('Richard Gere'),
('Mel Gibson'),
('Danny Glover'),
('Whoopi Goldberg'),
('Topher Grace'),
('Heather Graham'),
('Cary Grant'),
('Hugh Grant'),
('Alec Guinness'),
('Gene Hackman'),
('Tom Hanks'),
('Charlton Heston'),
('Woody Harrelson'),
('Ed Harris'),
('Rachael Harris'),
('Richard Harris'),
('Rex Harrison'),
('Ethan Hawke'),
('Salma Hayek'),
('Ed Helms'),
('Audrey Hepburn'),
('Katharine Hepburn'),
('Paris Hilton'),
('Dustin Hoffman'),
('William Holden'),
('Katie Holmes'),
('Anthony Hopkins'),
('Rock Hudson'),
('Bonnie Hunt'),
('Helen Hunt'),
('Holly Hunter'),
('William Hurt'),
('Anjelica Huston'),
('Jeremy Irons'),
('Hugh Jackman'),
('Samuel L. Jackson'),
('Angelina Jolie'),
('James Earl Jones'),
('Tommy Lee Jones'),
('Chris Kattan'),
('Diane Keaton'),
('Michael Keaton'),
('Harvey Keitel'),
('Gene Kelly'),
('Grace Kelly'),
('Nicole Kidman'),
('Ben Kingsley'),
('Val Kilmer'),
('Greg Kinnear'),
('Burt Lancaster'),
('Diane Lane'),
('Jessica Lange'),
('Jude Law'),
('Christopher Lee'),
('Vivien Leigh'),
('Jack Lemmon'),
('Daniel Day-Lewis'),
('Laura Linney'),
('Lindsay Lohan'),
('Jennifer Lopez'),
('Sophia Loren'),
('Shirley MacLaine'),
('John Malkovich'),
('Ann Margret'),
('Steve Martin'),
('Marlee Matlin'),
('Walter Matthau'),
('Matthew McConaughey'),
('Frances McDormand'),
('Ewan McGregor'),
('Ian McKellen'),
('Steve McQueen'),
('Marilyn Monroe'),
('Demi Moore'),
('Julianne Moore'),
('Viggo Mortensen'),
('Brittany Murphy'),
('Eddie Murphy'),
('Bill Murray'),
('Mike Myers'),
('Liam Neeson'),
('Paul Newman'),
('Jack Nicholson'),
('Nick Nolte'),
('Edward Norton'),
('Gary Oldman'),
('Laurence Olivier'),
('Ryan ONeal'),
('Haley Joel Osment'),
('Peter OToole'),
('Al Pacino'),
('Gwyneth Paltrow'),
('Sarah Jessica Parker'),
('Bill Paxton'),
('Gregory Peck'),
('Sean Penn'),
('Michelle Pfeiffer'),
('River Phoenix'),
('Jada Pinkett-Smith'),
('Brad Pitt'),
('Sidney Poitier'),
('Natalie Portman'),
('Dennis Quaid'),
('Anthony Quinn'),
('Robert Redford'),
('Vanessa Redgrave'),
('Tara Reid'),
('Keanu Reeves'),
('Burt Reynolds'),
('Julia Roberts'),
('Geoffrey Rush'),
('Kurt Russell'),
('Rene Russo'),
('Meg Ryan'),
('Winona Ryder'),
('Adam Sandler'),
('Susan Sarandon'),
('Roy Scheider'),
('Arnold Schwarzenegger'),
('George C. Scott'),
('Peter Sellers'),
('Elisabeth Shue'),
('Will Smith'),
('Wesley Snipes'),
('Sissy Spacek'),
('Kevin Spacey'),
('Sylvester Stallone'),
('Rod Steiger'),
('James Stewart'),
('Ben Stiller'),
('Sharon Stone'),
('Meryl Streep'),
('Kiefer Sutherland'),
('Hilary Swank'),
('Jessica Tandy'),
('Elizabeth Taylor'),
('Charlize Theron'),
('Emma Thompson'),
('Billy Bob Thornton'),
('Uma Thurman'),
('Spencer Tracy'),
('John Travolta'),
('Kathleen Turner'),
('Liv Tyler'),
('Vince Vaughn'),
('Jon Voight'),
('Mark Wahlberg'),
('Christopher Walken'),
('Denzel Washington'),
('Naomi Watts'),
('John Wayne'),
('Sigourney Weaver'),
('Orson Welles'),
('Robin Williams'),
('Bruce Willis'),
('Owen Wilson'),
('Debra Winger'),
('Kate Winslet'),
('Elijah Wood'),
('Natalie Wood'),
('James Woods'),
('Steve Zahn'),
('Renee Zellweger'),
('Catherine Zeta-Jones'),
(' '),
('Woody Allen	'),
('Michael Mann'),
('Robert Altman'),
('Mike Nichols'),
('Tim Burton	'),
('Roman Polanski'),
('James Cameron'),
('Martin Scorsese'),
('Frank Capra'),
('Ridley Scott'),
('Coen Brothers'),
('Night Shyamalan'),
('George Cukor	'),
('Steven Soderbergh'),
('Michael Curtiz	'),
('Stephen Speilberg'),
('Cecil B. Demille'),
('George Stevens'),
('Clint Eastwood	'),
('Oliver Stone'),
('John Ford'),
('Quentin Tarantino'),
('Alfred Hitchcock'),
('Peter Weir'),
('Ron Howard'),
('Orson Welles'),
('John Huston	'),
('Billy Wilder'),
('Elia Kazan'),
('Robert Wise'),
('Stanley Kubrick	'),
('John Woo'),
('David Lean'),
('William Wyler'),
('Spike Lee	'),
('Robert Zemeckis'),
('George Lucas	'),
('Fred Zinnemann'),
('Sidney Lumet	'),
('Adam Strange'),
('Aquaman'),
('Barbara Gordon'),
('Barry Allen (The Flash)'),
('Batman'),
('Beast'),
('Black Canary'),
('Black Lightning'),
('Black Panther'),
('Black Widow'),
('Blade'),
('Blue Beetle'),
('Booster Gold'),
('Bucky Barnes'),
('Captain America'),
('Captain Britain'),
('Captain Marvel'),
('Catwoman'),
('Cerebus'),
('Cyclops'),
('Daredevil'),
('Dashiell Bad Horse'),
('Deadpool'),
('Dick Grayson (Robin)'),
('Donna Troy'),
('Dr. Strange'),
('Dream of the Endless'),
('Elijah Snow'),
('Eric OGrady (Ant-Man)'),
('Fone Bone'),
('Gambit'),
('Ghost Rider'),
('Green Arrow'),
('Groo'),
('Hal Jordan (Green Lantern)'),
('Hank Pym (Ant-Man)'),
('Hawkeye'),
('Hawkman'),
('Hellboy'),
('Human Torch'),
('Invisible Woman'),
('Iron Fist'),
('Iron Man'),
('James Gordon'),
('Jean Grey'),
('Jesse Custer'),
('John Constantine'),
('John Stewart (Green Lantern)'),
('Jonah Hex'),
('Judge Dredd'),
('Ka-Zar'),
('Kitty Pryde'),
('Luke Cage'),
('Martian Manhunter'),
('Marv'),
('Michonne'),
('Mitchell Hundred'),
('Moon Knight'),
('Nick Fury'),
('Nightcrawler'),
('Nova'),
('Professor X'),
('Punisher'),
('Raphael'),
('Reed Richards'),
('Renee Montoya'),
('Rick Grimes'),
('Rorschach'),
('Savage Dragon'),
('Scott Pilgrim'),
('Sgt. Rock'),
('She-Hulk'),
('Silver Surfer'),
('Spawn'),
('Spider-Man'),
('Spider Jerusalem'),
('Storm'),
('Sub-Mariner'),
('Superboy'),
('Supergirl'),
('Superman'),
('Swamp Thing'),
('The Atom'),
('The Crow'),
('The Falcon'),
('The Hulk'),
('The Rocketeer'),
('The Spectre'),
('The Spirit'),
('The Thing'),
('The Tick'),
('Thor'),
('Tim Drake (Robin)'),
('Usagi Yojimbo'),
('Wally West (The Flash)'),
('Wasp'),
('Wildcat'),
('Wolverine'),
('Wonder Woman'),
('Yorick Brown'),
('James Patterson'),
('David Baldacci'),
('Nora Roberts'),
('Michael Connelly'),
('J D Robb'),
('C J Box'),
('Robyn Carr'),
('Julia Quinn'),
('Lee Child'),
('Christine Feehan'),
('Janet Evanovich'),
('Stuart Woods'),
('John Grisham'),
('John Sandford'),
('Clive Cussler'),
('Debbie Macomber'),
('Catherine Coulter'),
('Louise Penny'),
('Danielle Steel'),
('J R Ward'),
('J A Jance'),
('Jim Butcher'),
('Elin Hilderbrand'),
('Harlan Coben'),
('Sarah J Maas'),
('Patricia Briggs'),
('Lisa Gardner'),
('Joanne Fluke'),
('Karin Slaughter'),
('Anne Perry'),
('Jayne Ann Krentz'),
('Lisa Kleypas'),
('Brandon Sanderson'),
('Heather Graham'),
('Lynsay Sands'),
('Sandra Brown'),
('Julie Garwood'),
('Linda Howard'),
('M C Beaton'),
('Susan Mallery'),
('Craig Johnson'),
('Brad Thor'),
('Mary Higgins Clark'),
('Stephen King'),
('Robert Crais'),
('Diana Palmer'),
('Daniel Silva'),
('Nalini Singh'),
('Dean Koontz'),
('William Kent Krueger'),
('Kathy Reichs'),
('Fern Michaels'),
('Sherrilyn Kenyon'),
('Kyle Mills'),
('Rick Riordan'),
('Johanna Lindsey'),
('William W Johnstone'),
('Ilona Andrews'),
('Iris Johansen'),
('Douglas Preston'),
('Lisa Jackson'),
('Tom Clancy'),
('Mary Balogh'),
('Eric Vall'),
('Robert B Parker'),
('Laurell K Hamilton'),
('Anthony Horowitz'),
('Amanda Quick'),
('Jeffery Deaver'),
('Kristin Hannah'),
('Tami Hoag'),
('Jeffrey Archer'),
('David Rosenfelt'),
('James Rollins'),
('Jenn McKinlay'),
('Rhys Bowen'),
('Jude Deveraux'),
('Charlaine Harris'),
('J K Rowling'),
('Karen Kingsbury'),
('Bernard Cornwell'),
('Patricia Cornwell'),
('Ken Follett'),
('Maya Banks'),
('Alexander McCall Smith'),
('Charles Todd'),
('Richard Paul Evans'),
('Vince Flynn'),
('Gena Showalter'),
('Ann Cleeves'),
('Steve Berry'),
('David Weber'),
('Jonathan Kellerman'),
('John Connolly'),
('Mercedes Lackey'),
('Ellen Hopkins'),
('Linda Castillo'),
('Kristen Ashley'),
('Jacqueline Winspear'),
('Ace Atkins'),
('Nelson DeMille'),
('Tess Gerritsen'),
('Sherryl Woods'),
('Kate Carlisle'),
('Allison Brennan'),
('Terry Brooks'),
('RaeAnne Thayne'),
('Logan Jacobs'),
('Thomas Perry'),
('Colleen Hoover'),
('Elly Griffiths'),
('Sharon Sala'),
('Mark Greaney'),
('Diana Gabaldon'),
('Philippa Gregory'),
('Erin Hunter'),
('Kelley Armstrong'),
('Susan Stoker'),
('Cassandra Clare'),
('Jill Shalvis'),
('Linda Lael Miller'),
('Tana French'),
('Marc Cameron'),
('Eloisa James'),
('Jennifer L Armentrout'),
('Ellery Adams'),
('Lora Leigh'),
('Lisa Scottoline'),
('Jennifer Ashley'),
('Nicholas Sparks'),
('Donna Andrews'),
('Donna Leon'),
('Juno Wells'),
('John Le Carré'),
('Dan Brown'),
('Stephanie Laurens'),
('Grace Burrowes'),
('Robert Dugoni'),
('Hannah Howell'),
('James Lee Burke'),
('Susan Wiggs'),
('Laura Childs'),
('Amanda Flower'),
('Greg Iles'),
('Christina Dodd'),
('Rebecca Zanetti'),
('Agatha Christie'),
('Gregg Hurwitz'),
('Susan Wittig Albert'),
('Leslie Meier'),
('Kat Martin'),
('Carolyn Brown'),
('Robert Galbraith'),
('Jana DeLeon'),
('Jessie Cooke'),
('Karen Rose'),
('Marie Force'),
('Amelia Hutchins'),
('Elizabeth George'),
('Colleen Coble'),
('W E B Griffin'),
('Tracie Peterson'),
('Wanda E Brunstetter'),
('Victoria Thompson'),
('Alex Kava'),
('Brian Freeman'),
('Miranda James'),
('Kay Hooper'),
('Shelly Laurenston'),
('Karen Robards'),
('Faye Kellerman'),
('Alexandra Ivy'),
('Brad Taylor'),
('Vicki Delany'),
('Jack Higgins'),
('Alex Berenson'),
('Dav Pilkey'),
('Jenny Colgan'),
('Brenda Novak'),
('Jeaniene Frost'),
('Jayne Castle'),
('Janet Dailey'),
('Ruth Ware'),
('Joseph Finder'),
('Deborah Crombie'),
('Judith McNaught'),
('Lincoln Child'),
('Terry Goodkind'),
('Donna Grant'),
('Jo Nesbø'),
('Paige Shelton'),
('Kim Harrison'),
('Wilbur Smith'),
('Holly Black'),
('Thea Stilton'),
('Anna Lee Huber'),
('Lori Foster'),
('Lorraine Heath'),
('George R R Martin'),
('Nevada Barr'),
('Shelley Shepard Gray'),
('Beverly Lewis'),
('Catherine Anderson'),
('Sabrina Jeffries'),
('Michael Anderle'),
('Peter Robinson'),
('Tui T Sutherland'),
('John Flanagan'),
('Anne McCaffrey'),
('Ernest Cline'),
('Kresley Cole'),
('G A Aiken'),
('Elizabeth Hoyt'),
('Lani Lynn Vale'),
('Dana Stabenow'),
('Tessa Dare'),
('Rita Mae Brown'),
('L J Shen'),
('Seanan McGuire'),
('Lisa Jewell'),
('Ian Rankin'),
('Alan Bradley'),
('Andrew Rowe'),
('Jodi Picoult'),
('Cleo Coyle'),
('C S Harris'),
('Leigh Bardugo'),
('Melinda Leigh'),
('Faith Hunter'),
('Stephanie Hudson'),
('Kendra Elliot'),
('Carl Hiaasen'),
('Andrew Child'),
('Pamela Kelley'),
('Stephenie Meyer'),
('Stephen Hunter'),
('Darlene Gardner'),
('Ben Coes'),
('Matthew Reilly'),
('Sarah MacLean'),
('Jeff Lindsay'),
('Elizabeth Peters'),
('Andrew Grant'),
('Krista Davis'),
('V C Andrews'),
('Suzanne Wright'),
('Jan Karon'),
('Charles Finch'),
('Rachel Caine'),
('Laurie R King'),
('Lisa Wingate'),
('Darynda Jones'),
('Paul Doiron'),
('Ashley & JaQuavis'),
('Karen Harper'),
('John Ringo'),
('Lara Adrian'),
('Randy Wayne White'),
('Lauraine Snelling'),
('Val McDermid')